export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const NEW_USER = 'NEW_USER';
export const LOGIN_REQUEST_LOADING = 'LOGIN_REQUEST_LOADING';
export const SIGN_UP_REQUEST_LOADING = 'SIGN_UP_REQUEST_LOADING';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';
